### ISSUE TITLE
how to run on Console App c# 

### ISSUE THREAD

**Issue by huudatk53** [3ventic/EvtSource#15]
I want to Console.WriteLine Message. But not working. Something wrong with me
![image](https://user-images.githubusercontent.com/13384935/150263117-df1d612a-21ae-42ae-a9b8-8e7f45969e1c.png)

![image](https://user-images.githubusercontent.com/13384935/150263178-9cec5dfa-076c-4938-bdfb-64fa1a702353.png)

**Comment by 3ventic** [comment]
Your `Main` runs to the end and exits. There are a number of ways to keep the application running while work is being done in other threads, the simplest of which is likely `Console.ReadLine();` at the end of `Main`. Either way this is not an issue with EvtSource.
