### ISSUE TITLE
StreamReader.EndOfStream is blocking execution of the thread EventSourceReader.Start is called on

### ISSUE THREAD

**Issue by kaitlynbrown** [3ventic/EvtSource#2]
In the application I'm working on, I use this library to listen for messages pushed by my server. However, I discovered that any time a message would be received, my UI would freeze. It would stay frozen until either another message was received (which would cause it to unfreeze and then re-freeze) or until the connection was refreshed.

I discovered that in line 100 of `EventSourceReader`, when it tries to evaluate `sr.EndOfStream`, a value isn't returned until either more data is received or the connection is closed. So execution stops here and blocks the thread, instead of unblocking at line 102 as I assume it is meant to.

I can work around the issue by wrapping the call to `EventSourceReader.Start()` inside of a `Task.Run()`, but it seems unintentional that an async method would actually block execution of the thread it is running on, so I figured I'd create this issue.

**Comment by 3ventic** [comment]
I'll look into this this weekend, thanks.

**Comment by 3ventic** [comment]
[`EndOfStream`](https://docs.microsoft.com/dotnet/api/system.io.streamreader.endofstream?view=netcore-2.0#System_IO_StreamReader_EndOfStream) shouldn't be waiting for anything and [`Start()` doesn't wait for `ReaderAsync()` at all and returns immediately](https://github.com/3ventic/EvtSource/blob/master/EvtSource/EventSourceReader.cs#L62). I'm not convinced what you're seeing is caused by EvtSource. Are you using the latest version?

**Comment by kaitlynbrown** [comment]
I had the latest version as of my post, but it looks like that file was updated yesterday.
I am sure that it is blocking on `EndOfStream`. 
The issue isn't that it blocks on the initial `Start()` call. Code inside of an `async` method still actually runs on the same thread that called it, even when it resumes after an await. When `Start()` is called, it executes up until line 98 where it waits for the first event to be received. In this state everything is fine because while waiting it has ceded control to other tasks on the thread. After the first event is received, it executes through the while loop until it has parsed the event. It then emits the event and returns to the top of the while loop where it blocks on `EndOfStream` until the next message is received. If `Start()` was called on the UI thread, this will cause the UI to freeze.
FYI: The implementation of StreamReader is found here: https://referencesource.microsoft.com/#mscorlib/system/io/streamreader.cs
You can see that EndOfStream calls ReadBuffer() which is where I'm guessing  it gets stuck.

**Comment by 3ventic** [comment]
I'll look into an alternative. I haven't noticed it blocking as the only SSE URL I've used it against constantly sends ~400-900 events a second.

**Comment by 3ventic** [comment]
EndOfStream has been removed in 2.0
